### PR TITLE
Export container

### LINKED ISSUE #14: Go 1.10 incompatibility
Hi,

Due to change https://github.com/golang/go/issues/21353 (report: https://github.com/golang/go/issues/21357), calling `json.Unmarshal` on anything containing a `collins.Response` struct will fail when built with Go 1.10 due to the private `container` field containing an unexported struct: https://github.com/tumblr/go-collins/blob/master/collins/collins.go#L65-L74

For now I have a local workaround, but I will defer to the maintainers on how to deal with this (either export the object, or remove it altogether as it doesn't seem to be used anywhere internally once set: https://github.com/tumblr/go-collins/blob/master/collins/collins.go#L267-L275).

### PR DESCRIPTION
**Pull request by defect**
This exports the container struct to fix #14. I'm also adding golang 1.10 to the travis test suite.

@byxorna @qx-xp @roymarantz @aeriff

### CODE REVIEW

File: collins/collins.go [hunk 1]
```diff
@@ -53,7 +53,7 @@ type Error struct {
 	} `json:"data"`
 }
 
-type container struct {
+type Container struct {
```
Comment (byxorna) [inline collins/collins.go]: now that you are exporting this type, you should add comments for `godoc` please: http://elliot.land/post/godoc-tips-tricks

**Comment by bitfehler** [comment]
Hey, could this be merged? We are also interested in having this :smile_cat:
